### PR TITLE
improve code

### PR DESCRIPTION
**Pull request by epicstride**
Well i think its an improvement

### CODE REVIEW

**Comment by ReikaKalseki** [comment]
Pull request, meet anus.

**Comment by Kolatra** [comment]
what

**Comment by Kolatra** [comment]
the

**Comment by Kolatra** [comment]
fuck

**Comment by Kolatra** [comment]
I think we have a new language on our hands here.

**Comment by HellFirePvP** [comment]
Time to write a converter to convert it back :^)

**Comment by mezz** [comment]
How does this even happen?

**Comment by ProfessorProspector** [comment]
That must've taken some serious work to make this happen...

**Comment by Drullkus** [comment]
What the hell did I look at?

**Comment by ProfessorProspector** [comment]
It's like our worst chisel GUI contest, but with code.

**Comment by ThatGamerBlue** [comment]
well......

**Comment by auxiliary-character** [comment]
But why?

**Comment by Xireka** [comment]
Looks awesome, if you like half hidden stuff and unclear changes... I tried checking out of curiosity what the changes where by clicking myself through it and then pc lagged I was like "haha, nope!"

**Pull request closed without merging**
